suorganizer/urls.py
from django.contrib import admin
from django.urls import path

from organizer.views import homepage

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", homepage),
]

blog/models.py
from django.db import models
from organizer.models import Startup, Tag

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length = 63)

    slug = models.SlugField(
        max_length= 63,
        help_text= 'A label for URL config',
        unique_for_month= 'pub_date'
    )

    text = models.TextField()
    pub_date = models.DateField(
        'date published',
        auto_now_add= True
    )

    tags = models.ManyToManyField(
        Tag, related_name= 'blog_posts')
    startups = models.ManyToManyField(
        Startup, related_name= 'blog_posts')

    def __str__ (self):
        return "{} on {}".format(
            self.title,
            self.pub_date.strftime("%Y-%m-%d")
        )
    
    class Meta():
        verbose_name = 'blog posts'
        ordering = ['-pub_date', 'title']
        get_latest_by = 'pub_date'

organizer/models.py
from django.db import models

# Create your models here.
class Tag(models.Model):

    name = models.CharField(
        max_length = 31, unique = True)

    slug = models.SlugField(
        max_length= 31,
        unique= True,
        help_text= 'A label for URL config'
    )

    def __str__(self):
        return self.name.title()

    class Meta():
        ordering = ['name']


class Startup(models.Model):
    name = models.CharField(
        max_length= 31, db_index= True)

    slug = models.SlugField(
        max_length= 31,
        unique= True,
        help_text= 'A label for URL config'
    )

    description = models.TextField()

    founded_date = models.DateField( 'date founded')

    contact = models.EmailField()

    website = models.URLField(max_length= 255)

    tags = models.ManyToManyField(Tag)

    def __str__ (self):
        return self.name
    
    class Meta():
        ordering = ['name']
        get_latest_by = 'founded_date'

class NewsLink(models.Model):
    title = models.CharField(max_length= 63)

    pub_date = models.DateField('date published')

    link = models.URLField(max_length= 255)

    startup = models.ForeignKey(Startup, on_delete= models.CASCADE)

    def __str__(self):
        return "{} : {}".format(
            self.startup, self.title
        )

    class Meta():
        verbose_name = 'news article'
        ordering = ['-pub_date']
        get_latest_by = 'pub_date'

blog/views.py
from django.shortcuts import render

# Create your views here.

organizer/views.py
from django.shortcuts import render
from django.template import Context, loader
from django.http.response import HttpResponse

from .models import Tag

def homepage(request):
    tag_list = Tag.objects.all()
    template = loader.get_template('organizer/tag_list.html')
    context = Context({'tag_list' : tag_list})
    html_output = template.render(context)
    return HttpResponse(html_output)

# Create your views here.

blog/templates/blog/base_blog.html
{% extends parent_template|default:"base.html" %}

blog/templates/blog/post_detail.html
<article>

    <header>
        <h2> {{ post.title|title }} </h2>
        <p>
            Written on
            <time datetime= "{{ post.pub_date|date:"Y-m-d"}}">
                {{ post.pub_date|date:"l, F j, Y"}}
            </time>
        </p>
    </header>

    {{ post.text|linebreaks }}

    {% if post.startups.all or post.tags.all %}
    <footer>
        
        {% if posts.startups.all %}
            <section>
                <h3>Startup{{ post.starttups.count|pluralize }}</h3>
                <ul>
                    {% for startup in post.startups.all %}
                        <li><a href = "">
                            {{ startup.name}}
                        </a></li>
                    {% endfor %}
                </ul>
            </section>
        {% endif %}

        {% if posts.tags.all %}
            <section>
                <h3>Tag{{ post.tags.count|pluralize }}</h3>
                <ul>
                    {% for tag in post.tag.all %}
                        <li><a href = "">
                            {{ tag.name|title}}
                        </a></li>
                    {% endfor %}
                </ul>
            </section>
        {% endif %}

    </footer>
    {% endif %}
    
</article>

blog/templates/blog/post_list.html
{% for post in post_list %}
    <article>
        <header>
            <h2>
                <a href = "">
                    {{ post.title|title}}</a>
            </h2>
            <p>
                Written on:
                <time datetime= "{{ post.pub_date|date: "Y-m-d"}}">
                    {{post.pub_date|date: "l, F j, Y"}}
                </time>
            </p>
        </header>
        <p>{{ post.text|truncatewords:20 }}</p>
        <p>
            <a href= "">
                Readmore&hellip;</a>
        </p>
    </article>
    {% empty%}
        <p><em> No Blog Posts Available</em></p>
{% endfor %}

organizer/templates/organizer/base_organizer.html
{% extends parent_template|default:"base.html" %}

organizer/templates/organizer/startup_detail.html
<article>

    <h2>{{ startup.name }}</h2>
    <dl>
        <dt>Date Founded</dt>
            <dd> {{ startup.founded_date|date: "F jS, Y" }} </dd>
        <dt>Website</dt>
            <dd> {{ startup.website }} </dd>
        <dt>Contact</dt>
            <dd> {{ startup.contact }} </dd>

            <dt>Tag {{ startup.tags.count|pluralize }} </dt>
                {% for tag in startup.tags.all %}
                    <dd><a href = "">
                        {{ tag.name|title }}
                    </a></dd>
                {% endfor %}
    </dl>

    <p> {{ startup.description }} </p>
        {% if startup.newslink_set.all %}
            <section>
                <h3>Recent News</h3>
                <ul>
                    {% for newslink in startup.newslink_set.all %}
                    <li>
                        <a href = "{{ newslink.link }}">
                            {{ newslink.title|title }}
                        </a>
                    </li>
                    {% endfor %}
                </ul>
            </section>
        {% endif %}
            
        {% if startup.blog_posts.all %}
            <section>
                <h3>Blog Post{{ startup.blog_posts.all|title }}</h3>
                <ul>
                    {% for post in startup.blog_posts.all %}
                    <li>
                        <a href = "">
                            {{ post.title|title }}
                        </a>
                    </li>
                    {% endfor %}
                </ul>
            </section>
        {% endif %}

</article>

organizer/templates/organizer/startup_list.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Startups
{% endblock %}

{% block content %}
<h2>Startup List</h2>
<ul>
    {% for startup in startup_list %}
        <li>
            <a href="">
                {{ startup.name}}  
            </a>
        </li>
    {% empty %}
        <li>
            <em>No Startups Available</em>
        </li>
    {% endfor %}
</ul>
{% endblock %}

organizer/templates/organizer/tag_detail.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - {{ tag.name|title }}
{% endblock %}

{% block content %}

<h2> {{tag.name|title}} </h2>
{% if tag.startup_set.all %}
    <section>
        <h3>Startups{{ tag.startup_set.all|count|pluralize }}</h3>
        <p>
            Tag is associated with
            {{ tag.startup_set.all|count }}
            startups{{ tag.startup_set.all|count|pluralize }}.
        </p>
        <ul>
            {% for startup in tag.startup_set.all %}
                <li><a href = "">
                    {{ startup.name }}
                </a></li>
            {% endfor %}
        </ul>
    </section>
{% else %} 
    <p> This is not related to any startups. </p>
{% endif %}
    {% if tag.blog_posts.all%}
        <section>
            <h3>Blog Posts{{ tag.blog_posts.all|count|pluralize }}</h3>
            <ul>
                {% for post in tab.blog_posts.all %}
                    <li><a href = "">
                        {{ post.title|title }}
                    </a></li>
                {% endfor %}
            </ul>
        </section>
    {% endif%}
    {% if not tag.startup_set.all and not tag.blog_posts.all %}
        <p> This tag is not related to any blog posts. </p>
    {% endif %}
{% endblock %}

organizer/templates/organizer/tag_list.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block  title %}
{{ block.super }} - Tag List
{% endblock %}

{% block content %}

<h2>Tag List </h2>
<ul>
    {% for tag in tag_list %}
        <li>
            <a href = "">
                {{ tag.name|title }}
            </a>
        </li>
    {% empty %}
        <li><em>There are currently no Tags available.</em></li>
    {% endfor %}
</ul>
{% endblock  %}

templates/base.html
<!DOCTYPE html>
    <html lang="en">
        <head>
            <meta charset="utf-8">
            <title>
               {% block title%}
                Startup Organizer
               {% endblock %}
            </title>
            <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
            <meta name="viewport" content="width=device-width, initial-scale=1">
        </head>

        <body>
             <div>
                 <header>
                     <h1> Startup Organizer
                 </header>
                 <main>
                    {% block content%}
                     This is a default content
                    {% endblock %}
                </main>
            </div>

            <footer>
                <p>
                    &copy; 2015
                    <a href= "https://Django-Unleashed.com/">
                        Django </a>
                </p>
            </footer>
        </body>
    </html>